# Generated by Django 4.2.7 on 2023-12-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="project",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
