# Generated by Django 4.2.7 on 2023-12-22 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employer", "0001_initial"),
        ("core", "0003_employer_invitation_employeeprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="employer",
        ),
        migrations.AlterModelOptions(
            name="punchinuser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="punchinuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="punchinuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="punchinuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="punchinuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="punchinuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employer.employer",
            ),
        ),
        migrations.AlterField(
            model_name="punchinuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="punchinuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="punchinuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Employer",
        ),
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
