# Generated by Django 5.0 on 2024-01-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_punchinuser_is_employer"),
        ("employer", "0005_employerprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="employer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="employer.employer"
            ),
        ),
    ]
