# Generated by Django 5.0.1 on 2024-01-08 04:55

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employer_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=10, unique=True
                    ),
                ),
                ("employer_name", models.CharField(max_length=255)),
                ("employer_address", models.CharField(blank=True, max_length=255)),
                ("employer_city", models.CharField(blank=True, max_length=255)),
                ("employer_state", models.CharField(blank=True, max_length=255)),
                ("employer_zip_code", models.CharField(blank=True, max_length=10)),
                (
                    "employer_email_address",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "employer_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "employer_ein_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "employee_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_profile",
                        to="core.employeeprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_view_employer_dashboard", "Can view employer dashboard"),
                    ("can_send_invitations", "Can send invitations"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("is_accepted", models.BooleanField(default=False)),
                ("expiration_date", models.DateTimeField()),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employer.employer",
                    ),
                ),
            ],
        ),
    ]
