# Generated by Django 5.0.1 on 2024-01-09 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employer",
            name="employee_profile",
        ),
    ]
