# Generated by Django 4.2.7 on 2023-12-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employer", "0002_alter_employer_employer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="employer_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employer",
            name="employer_city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employer",
            name="employer_state",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employer",
            name="employer_zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
