# Generated by Django 5.0.1 on 2024-01-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employer", "0002_remove_employer_employee_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="activated",
            field=models.BooleanField(default=False),
        ),
    ]
