# Generated by Django 5.0.1 on 2024-01-11 04:19

import django.db.models.deletion
import employer.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employer", "0003_employerprofile_activated"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employer.employer",
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="employer_id",
            field=models.CharField(
                default=employer.models.generate_employer_id,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
    ]
