# Generated by Django 5.0.1 on 2024-01-09 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("employer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employer.employer",
            ),
        ),
    ]
