# Generated by Django 4.2.7 on 2023-12-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="punchinuser",
            name="is_employer",
            field=models.BooleanField(default=False),
        ),
    ]
