# Generated by Django 5.0.1 on 2024-01-09 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_employeeprofile_employer"),
        ("employer", "0002_remove_employer_employee_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profiles",
                to="employer.employer",
            ),
        ),
    ]
