"""Add first name and last name to user

Revision ID: 46264f36d744
Revises: 3081e080ad5c
Create Date: 2023-09-12 00:40:47.950057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46264f36d744'
down_revision = '3081e080ad5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
