# Generated by Django 4.2.7 on 2023-12-22 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employer",
            old_name="name",
            new_name="employer_name",
        ),
        migrations.RemoveField(
            model_name="employer",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="employer",
            name="contact_phone_number",
        ),
        migrations.AddField(
            model_name="employer",
            name="company_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, unique=True
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="employer_ein_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="employer_email_address",
            field=models.EmailField(
                db_index=True, default=1, max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employer",
            name="employer_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, unique=True
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="employer_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, unique=True
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="user",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
