# Generated by Django 4.2.7 on 2023-12-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="employer_id",
            field=models.CharField(
                db_index=True, editable=False, max_length=10, unique=True
            ),
        ),
    ]
