# Generated by Django 4.2.7 on 2023-12-22 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employer", "0003_employer_employer_address_employer_employer_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employer",
            options={
                "permissions": [
                    ("can_view_employer_dashboard", "Can view employer dashboard"),
                    ("can_send_invitations", "Can send invitations"),
                ]
            },
        ),
    ]
