# Generated by Django 5.0 on 2024-01-07 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_employeeprofile_employer"),
        ("employer", "0005_employerprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="employee_profile",
            field=models.OneToOneField(
                default=8934567891,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_profile",
                to="core.employeeprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
